"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import {
  ArrowLeft, ArrowUpRight, Check, FileText, Headphones, Image as ImageIcon,
  Loader2, Plus, Trash2, Upload, Video, X, Eye,
} from "lucide-react";
import { FormEvent, useEffect, useRef, useState, type ReactNode } from "react";
import {
  getAdminCategories, getAdminResource, updateResource,
  type AdminCategory, type AdminResource, type UpdateResourceInput,
  type ResourceType, type MediaType, type MediaProvider,
} from "@/lib/admin-api";

interface MediaItem {
  id?: string; type: MediaType; provider: MediaProvider; title: string; url: string; externalId: string;
  storageKey?: string; mimeType?: string; fileSize?: number; uploading?: boolean; fileName?: string; localPreviewUrl?: string;
}
const resourceTypes: { value: ResourceType; label: string }[] = [
  { value: "SERMON", label: "Sermon" }, { value: "EBOOK", label: "Ebook" }, { value: "SONG", label: "Song" },
  { value: "VIDEO", label: "Video" }, { value: "PODCAST", label: "Podcast" }, { value: "ARTICLE", label: "Article" },
];
const mediaTypes: { value: MediaType; label: string }[] = [
  { value: "VIDEO", label: "Video" }, { value: "AUDIO", label: "Audio" }, { value: "PDF", label: "PDF" }, { value: "IMAGE", label: "Image" },
];
const mediaProviders: { value: MediaProvider; label: string }[] = [
  { value: "YOUTUBE", label: "YouTube" }, { value: "CLOUDINARY", label: "Cloudinary" }, { value: "EXTERNAL", label: "External URL" },
];
function cloudinaryConfig() { const cloudName = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME; const uploadPreset = process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET; if (!cloudName || !uploadPreset) throw new Error("Cloudinary upload is not configured."); return { cloudName, uploadPreset }; }
function inferMediaType(file: File): MediaType { if (file.type.startsWith("audio/")) return "AUDIO"; if (file.type === "application/pdf") return "PDF"; if (file.type.startsWith("image/")) return "IMAGE"; return "VIDEO"; }
async function uploadToCloudinary(file: File) { const { cloudName, uploadPreset } = cloudinaryConfig(); const form = new FormData(); form.append("file", file); form.append("upload_preset", uploadPreset); form.append("folder", "olawale-smith-ministries/resources"); const r = await fetch(`https://api.cloudinary.com/v1_1/${cloudName}/auto/upload`, { method: "POST", body: form }); const p = await r.json(); if (!r.ok || !p.secure_url) throw new Error(p.error?.message || "Cloudinary upload failed."); return p as { secure_url: string; public_id?: string; bytes?: number };
}
function slugify(v: string) { return v.toLowerCase().trim().replace(/[^a-z0-9\s-]/g, "").replace(/\s+/g, "-").replace(/-+/g, "-"); }

export default function EditResourcePage() {
  const router = useRouter(); const params = useParams(); const resourceId = typeof params.id === "string" ? params.id : "";
  const [loading, setLoading] = useState(true); const [loadingError, setLoadingError] = useState("");
  const [categoriesLoading, setCategoriesLoading] = useState(true); const [categoriesError, setCategoriesError] = useState("");
  const [title, setTitle] = useState(""); const [slug, setSlug] = useState(""); const [description, setDescription] = useState(""); const [content, setContent] = useState("");
  const [type, setType] = useState<ResourceType>("SERMON"); const [speaker, setSpeaker] = useState(""); const [featured, setFeatured] = useState(false); const [published, setPublished] = useState(false);
  const [categories, setCategories] = useState<AdminCategory[]>([]); const [selectedCategoryIds, setSelectedCategoryIds] = useState<string[]>([]); const [media, setMedia] = useState<MediaItem[]>([]);
  const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [showPreview, setShowPreview] = useState(false); const [showSuccess, setShowSuccess] = useState(false);
  const fileInputs = useRef<Record<number, HTMLInputElement | null>>({});

  async function loadResource() { if (!resourceId) { setLoading(false); return setLoadingError("Resource ID is missing."); } try { setLoading(true); setLoadingError(""); populateResource((await getAdminResource(resourceId)).data); } catch (e) { setLoadingError(e instanceof Error ? e.message : "Unable to load resource."); } finally { setLoading(false); } }
  async function loadCategories() { try { setCategoriesLoading(true); setCategoriesError(""); setCategories((await getAdminCategories()).data ?? []); } catch (e) { setCategoriesError(e instanceof Error ? e.message : "Unable to load categories."); } finally { setCategoriesLoading(false); } }
  useEffect(() => { loadResource(); loadCategories(); }, [resourceId]);
  function populateResource(r: AdminResource) { setTitle(r.title ?? ""); setSlug(r.slug ?? ""); setDescription(r.description ?? ""); setContent(r.content ?? ""); setType(r.type ?? "SERMON"); setSpeaker(r.speaker ?? ""); setFeatured(Boolean(r.featured)); setPublished(Boolean(r.published)); setSelectedCategoryIds((r.categories ?? []).map(x => x.categoryId ?? x.category?.id).filter((x): x is string => Boolean(x))); setMedia((r.media ?? []).map(m => ({ id: m.id, type: m.type, provider: m.provider, title: m.title ?? "", url: m.url ?? "", externalId: m.externalId ?? "", storageKey: m.storageKey ?? undefined, mimeType: m.mimeType ?? undefined, fileSize: typeof m.fileSize === "number" ? m.fileSize : undefined })))); }
  function toggleCategory(id: string) { setSelectedCategoryIds(c => c.includes(id) ? c.filter(x => x !== id) : [...c, id]); }
  function addMedia() { setMedia(c => [...c, { type: "VIDEO", provider: "YOUTUBE", title: "", url: "", externalId: "" }]); }
  function updateMedia(i: number, patch: Partial<MediaItem>) { setMedia(c => c.map((m, x) => x === i ? { ...m, ...patch } : m)); }
  function removeMedia(i: number) { setMedia(c => c.filter((_, x) => x !== i)); }
  async function handleFileUpload(index: number, file?: File) { if (!file) return; const mediaType = inferMediaType(file); const local = URL.createObjectURL(file); updateMedia(index, { type: mediaType, provider: "CLOUDINARY", uploading: true, fileName: file.name, localPreviewUrl: local, url: "", externalId: "" }); try { const p = await uploadToCloudinary(file); updateMedia(index, { provider: "CLOUDINARY", type: mediaType, uploading: false, url: p.secure_url, storageKey: p.public_id, mimeType: file.type, fileSize: p.bytes ?? file.size }); } catch (e) { URL.revokeObjectURL(local); updateMedia(index, { uploading: false, localPreviewUrl: undefined, url: "" }); setError(e instanceof Error ? e.message : "Unable to upload media."); } }
  function validateMedia() { for (let i = 0; i < media.length; i++) { const m = media[i]; if (m.uploading) return `Media ${i + 1}: Please wait for the upload to finish.`; if (!m.url.trim() && !m.externalId.trim()) continue; if (!m.type) return `Media ${i + 1}: Media type is required.`; if (m.provider !== "YOUTUBE" && !m.url.trim()) return `Media ${i + 1}: Please provide a media URL.`; } return ""; }
  async function handleSubmit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setError(""); const t = title.trim(), s = slug.trim(); if (!t) return setError("Please enter a resource title."); if (!s) return setError("Please enter a resource slug."); const mediaError = validateMedia(); if (mediaError) return setError(mediaError); try { setSaving(true); const input: UpdateResourceInput = { title: t, slug: s, description: description.trim() || undefined, content: content.trim() || undefined, type, speaker: speaker.trim() || undefined, featured, published, categoryIds: selectedCategoryIds, media: media.filter(m => m.url.trim() || m.externalId.trim()).map(m => ({ type: m.type, provider: m.provider, title: m.title.trim() || undefined, url: m.url.trim() || undefined, externalId: m.externalId.trim() || undefined, storageKey: m.storageKey, mimeType: m.mimeType, fileSize: m.fileSize })) }; await updateResource(resourceId, input); setShowSuccess(true); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update resource."); } finally { setSaving(false); } }

  if (loading) return <main className="flex min-h-screen items-center justify-center bg-ivory text-charcoal"><div className="flex items-center gap-3 text-sm text-charcoal/45"><Loader2 size={18} className="animate-spin text-bronze"/>Loading resource...</div></main>;
  if (loadingError) return <main className="min-h-screen bg-ivory px-6 py-10 text-charcoal"><div className="mx-auto max-w-xl border border-red-500/15 bg-white p-8"><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-red-500">Resource Error</p><h1 className="mt-2 text-2xl font-medium">Unable to load resource</h1><p className="mt-3 text-sm leading-6 text-charcoal/45">{loadingError}</p><div className="mt-6 flex gap-3"><button onClick={loadResource} className="bg-charcoal px-5 py-3 text-[10px] font-semibold uppercase tracking-[0.14em] text-ivory">Try Again</button><Link href="/admin/dashboard/resources" className="border border-charcoal/10 bg-white px-5 py-3 text-[10px] font-semibold uppercase tracking-[0.14em] text-charcoal/60">Back to Resources</Link></div></div></main>;

  return <main className="min-h-screen bg-ivory text-charcoal"><header className="border-b border-charcoal/10 bg-white"><div className="mx-auto max-w-[1400px] px-6 py-6 lg:px-10"><Link href="/admin/dashboard/resources" className="mb-4 inline-flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.14em] text-charcoal/45 hover:text-bronze"><ArrowLeft size={14}/>Back to Resources</Link><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-bronze">Content Management</p><h1 className="display-heading mt-2 text-3xl sm:text-4xl">Edit Resource</h1><p className="mt-2 max-w-xl text-sm leading-6 text-charcoal/45">Update the resource details, organization, publishing status, and attached media.</p></div></header>
    <div className="mx-auto max-w-[1400px] px-6 py-8 lg:px-10 lg:py-12"><form onSubmit={handleSubmit} className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-8">
      <section className="border border-charcoal/10 bg-white"><SectionHead eyebrow="Basic Information" title="Resource details"/><div className="space-y-6 p-6"><Field label="Title" required><input value={title} onChange={e => { setTitle(e.target.value); if (!slug.trim()) setSlug(slugify(e.target.value)); }} className="input" required/></Field><Field label="Slug" required hint="Used in the public resource URL."><input value={slug} onChange={e => setSlug(slugify(e.target.value))} className="input" required/></Field><div className="grid gap-6 sm:grid-cols-2"><Field label="Resource Type" required><select value={type} onChange={e => setType(e.target.value as ResourceType)} className="input">{resourceTypes.map(x => <option key={x.value} value={x.value}>{x.label}</option>)}</select></Field><Field label="Speaker"><input value={speaker} onChange={e => setSpeaker(e.target.value)} className="input"/></Field></div><Field label="Description"><textarea value={description} onChange={e => setDescription(e.target.value)} rows={5} className="input resize-y"/></Field><Field label="Article / Resource Content"><textarea value={content} onChange={e => setContent(e.target.value)} rows={14} className="input resize-y"/></Field></div></section>
      <section className="border border-charcoal/10 bg-white"><SectionHead eyebrow="Organization" title="Categories" description="Assign one or more categories to organize this resource."/><div className="p-6">{categoriesLoading ? <Loader2 className="animate-spin text-bronze"/> : categoriesError ? <p className="text-sm text-red-600">{categoriesError}</p> : categories.length === 0 ? <p className="border border-dashed border-charcoal/10 p-8 text-center text-sm text-charcoal/45">No categories have been created yet.</p> : <div className="grid gap-3 sm:grid-cols-2">{categories.map(c => { const selected = selectedCategoryIds.includes(c.id); return <button type="button" key={c.id} onClick={() => toggleCategory(c.id)} className={`flex items-start gap-3 border p-4 text-left ${selected ? "border-bronze bg-bronze/[0.06]" : "border-charcoal/10 hover:border-bronze/40"}`}><span className={`mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center border ${selected ? "border-bronze bg-bronze text-ivory" : "border-charcoal/20"}`}>{selected && <Check size={11}/>}</span><span><span className="block text-xs font-medium">{c.name}</span><span className="mt-1 block text-[10px] text-charcoal/35">/{c.slug}</span></span></button>})}</div>}{selectedCategoryIds.length > 0 && <p className="mt-4 text-[10px] font-semibold uppercase tracking-[0.12em] text-bronze">{selectedCategoryIds.length} {selectedCategoryIds.length === 1 ? "category" : "categories"} selected</p>}</div></section>
      <section className="border border-charcoal/10 bg-white"><div className="flex items-center justify-between border-b border-charcoal/10 px-6 py-5"><div><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-bronze">Media</p><h2 className="mt-2 text-xl font-medium">Attach media</h2><p className="mt-1 text-xs text-charcoal/40">Upload device files directly to Cloudinary before saving, or attach YouTube/external media.</p></div><button type="button" onClick={addMedia} className="inline-flex items-center gap-2 border border-charcoal/10 px-4 py-2.5 text-[10px] font-semibold uppercase tracking-[0.12em] hover:border-bronze hover:text-bronze"><Plus size={14}/>Add Media</button></div><div className="p-6">{media.length === 0 ? <div className="border border-dashed border-charcoal/10 px-6 py-12 text-center"><Video size={24} className="mx-auto text-charcoal/20"/><p className="mt-4 text-sm text-charcoal/45">No media attached yet.</p><button type="button" onClick={addMedia} className="mt-4 text-[10px] font-semibold uppercase tracking-[0.14em] text-bronze">Add your first media</button></div> : <div className="space-y-5">{media.map((m, i) => <MediaEditor key={m.id ?? `new-${i}`} item={m} index={i} onUpdate={p => updateMedia(i, p)} onRemove={() => removeMedia(i)} onFile={f => handleFileUpload(i, f)} fileInput={el => { fileInputs.current[i] = el; }}/>)}</div>}</div></section>
    </div><aside className="space-y-6"><section className="border border-charcoal/10 bg-white"><SectionHead eyebrow="Publishing" title="Visibility"/><div className="space-y-5 p-6"><Toggle label="Published" description="Make this resource visible on the public website." checked={published} onChange={setPublished}/><Toggle label="Featured" description="Highlight this resource in featured sections." checked={featured} onChange={setFeatured}/></div></section>{error && <div className="border border-red-500/15 bg-red-500/[0.03] p-5 text-sm leading-6 text-red-600">{error}</div>}<section className="border border-charcoal/10 bg-white p-6"><button type="button" onClick={() => setShowPreview(true)} className="flex w-full items-center justify-center gap-2 border border-charcoal/10 px-5 py-4 text-[10px] font-semibold uppercase tracking-[0.14em] hover:border-bronze hover:text-bronze"><Eye size={15}/>Preview Resource</button><button type="submit" disabled={saving || media.some(m => m.uploading)} className="mt-3 flex w-full items-center justify-center gap-2 bg-charcoal px-5 py-4 text-[10px] font-semibold uppercase tracking-[0.14em] text-ivory hover:bg-bronze disabled:opacity-50">{saving ? <><Loader2 size={15} className="animate-spin"/>Saving Changes...</> : <><Check size={15}/>Save Changes<ArrowUpRight size={14}/></>}</button><Link href="/admin/dashboard/resources" className="mt-3 flex w-full items-center justify-center gap-2 border border-charcoal/10 px-5 py-4 text-[10px] font-semibold uppercase tracking-[0.14em] text-charcoal/55"><X size={14}/>Cancel</Link></section></aside></form></div>
    {showPreview && <PreviewDialog title={title} description={description} content={content} type={type} speaker={speaker} media={media} onClose={() => setShowPreview(false)}/>} {showSuccess && <SuccessDialog onContinue={() => router.push("/admin/dashboard/resources")}/>}</main>;
}

function MediaEditor({ item, index, onUpdate, onRemove, onFile, fileInput }: { item: MediaItem; index: number; onUpdate: (p: Partial<MediaItem>) => void; onRemove: () => void; onFile: (f?: File) => void; fileInput: (el: HTMLInputElement | null) => void; }) {
  const icon = item.type === "AUDIO" ? <Headphones size={16}/> : item.type === "PDF" ? <FileText size={16}/> : item.type === "IMAGE" ? <ImageIcon size={16}/> : <Video size={16}/>;
  return <div className="border border-charcoal/10 p-5"><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center bg-bronze/10 text-bronze">{icon}</div><div><p className="text-xs font-medium">Media {index + 1}</p><p className="mt-1 text-[10px] uppercase tracking-[0.12em] text-charcoal/35">{item.type} · {item.provider}</p></div></div><button type="button" onClick={onRemove} className="flex h-8 w-8 items-center justify-center text-charcoal/30 hover:bg-red-50 hover:text-red-500"><Trash2 size={15}/></button></div>
    <div className="grid gap-5 sm:grid-cols-2"><Field label="Media Type"><select value={item.type} onChange={e => onUpdate({ type: e.target.value as MediaType })} className="input">{mediaTypes.map(x => <option key={x.value} value={x.value}>{x.label}</option>)}</select></Field><Field label="Provider"><select value={item.provider} onChange={e => onUpdate({ provider: e.target.value as MediaProvider, externalId: e.target.value === "YOUTUBE" ? item.externalId : "" })} className="input">{mediaProviders.map(x => <option key={x.value} value={x.value}>{x.label}</option>)}</select></Field></div>
    <div className="mt-5"><Field label="Media Title"><input value={item.title} onChange={e => onUpdate({ title: e.target.value })} className="input" placeholder="Walking in Purpose — Full Sermon"/></Field></div>
    <div className="mt-5 border border-dashed border-bronze/30 bg-bronze/[0.03] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.13em] text-bronze">Device Upload</p><p className="mt-1 text-[11px] leading-5 text-charcoal/40">Upload immediately to Cloudinary. Saving the resource is separate.</p></div><input data-media-upload={index} ref={fileInput} type="file" className="hidden" accept="audio/*,video/*,image/*,application/pdf" onChange={e => { onFile(e.target.files?.[0]); e.currentTarget.value = ""; }}/><button type="button" disabled={item.uploading} onClick={() => document.querySelector<HTMLInputElement>(`input[data-media-upload="${index}"]`)?.click()} className="inline-flex items-center gap-2 bg-charcoal px-4 py-2.5 text-[10px] font-semibold uppercase tracking-[0.12em] text-ivory disabled:opacity-50"><Upload size={14}/>{item.uploading ? "Uploading..." : "Choose File"}</button></div>{item.fileName && <p className="mt-3 truncate text-xs text-charcoal/55">{item.fileName}</p>}{item.url && item.provider === "CLOUDINARY" && <p className="mt-2 text-[10px] font-semibold uppercase tracking-[0.1em] text-green-700">Uploaded to Cloudinary</p>}</div>
    {item.provider !== "CLOUDINARY" && <><div className="mt-5"><Field label="URL" hint={item.provider === "YOUTUBE" ? "Paste the full YouTube URL." : "Paste the direct media URL."}><input type="url" value={item.url} onChange={e => onUpdate({ url: e.target.value })} placeholder={item.provider === "YOUTUBE" ? "https://youtu.be/..." : "https://..."} className="input"/></Field></div>{item.provider === "YOUTUBE" && <div className="mt-5"><Field label="YouTube Video ID" hint="Optional when the URL is provided."><input value={item.externalId} onChange={e => onUpdate({ externalId: e.target.value })} placeholder="XyCHesmYev0" className="input"/></Field></div>}</>}
    {item.provider === "CLOUDINARY" && item.url && <div className="mt-4 overflow-hidden border border-charcoal/10 bg-black">{item.type === "IMAGE" ? <img src={item.url} alt={item.title || "Uploaded media"} className="max-h-72 w-full object-contain"/> : item.type === "VIDEO" ? <video controls preload="metadata" className="max-h-72 w-full" src={item.url}/> : item.type === "AUDIO" ? <audio controls className="w-full p-4" src={item.url}/> : <div className="p-6 text-center text-sm text-white/70">PDF uploaded and ready.</div>}</div>}
  </div>;
}
function PreviewDialog({ title, description, content, type, speaker, media, onClose }: { title: string; description: string; content: string; type: ResourceType; speaker: string; media: MediaItem[]; onClose: () => void; }) { return <div className="fixed inset-0 z-50 overflow-y-auto bg-charcoal/60 p-4 backdrop-blur-sm"><div className="mx-auto my-8 max-w-4xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-charcoal/10 px-6 py-5"><div><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-bronze">Draft Preview</p><h2 className="mt-1 text-xl font-medium">Public Resource Preview</h2></div><button type="button" onClick={onClose} className="flex h-9 w-9 items-center justify-center border border-charcoal/10"><X size={16}/></button></div><div className="p-6 sm:p-10"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-bronze">{type}</p><h1 className="display-heading mt-3 text-4xl sm:text-5xl">{title || "Untitled resource"}</h1>{speaker && <p className="mt-4 text-xs font-semibold uppercase tracking-[0.12em] text-charcoal/45">{speaker}</p>}{description && <p className="mt-6 max-w-2xl text-base leading-8 text-charcoal/60">{description}</p>}{content && <div className="mt-8 whitespace-pre-wrap border-t border-charcoal/10 pt-8 text-sm leading-8 text-charcoal/70">{content}</div>}{media.filter(m => m.url).length > 0 && <div className="mt-10 space-y-6 border-t border-charcoal/10 pt-8">{media.filter(m => m.url).map((m, i) => <PreviewMedia key={i} media={m}/>)}</div>}</div></div></div>; }
function PreviewMedia({ media }: { media: MediaItem }) { if (media.provider === "YOUTUBE") { const id = media.externalId || media.url.match(/(?:v=|youtu\.be\/|shorts\/|embed\/)([^?&/]+)/)?.[1]; return id ? <iframe src={`https://www.youtube.com/embed/${id}`} title={media.title || "YouTube video"} className="aspect-video w-full bg-black" allowFullScreen/> : null; } if (media.type === "VIDEO") return <video controls className="max-h-[520px] w-full bg-black" src={media.url}/>; if (media.type === "AUDIO") return <audio controls className="w-full" src={media.url}/>; if (media.type === "IMAGE") return <img src={media.url} alt={media.title || "Resource image"} className="max-h-[520px] w-full object-contain"/>; return <a href={media.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-semibold text-bronze">Open PDF <ArrowUpRight size={14}/></a>; }
function SectionHead({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) { return <div className="border-b border-charcoal/10 px-6 py-5"><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-bronze">{eyebrow}</p><h2 className="mt-2 text-xl font-medium">{title}</h2>{description && <p className="mt-1 text-xs text-charcoal/40">{description}</p>}</div>; }
function Field({ label, required, hint, children }: { label: string; required?: boolean; hint?: string; children: ReactNode }) { return <div><label className="block text-[10px] font-semibold uppercase tracking-[0.14em] text-charcoal/50">{label}{required && <span className="ml-1 text-bronze">*</span>}</label>{hint && <p className="mt-1 text-[11px] leading-5 text-charcoal/35">{hint}</p>}<div className="mt-2">{children}</div></div>; }
function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (v: boolean) => void }) { return <button type="button" onClick={() => onChange(!checked)} className="flex w-full items-start gap-4 text-left"><span className={`relative mt-0.5 flex h-5 w-9 shrink-0 items-center rounded-full ${checked ? "bg-bronze" : "bg-charcoal/15"}`}><span className={`absolute h-3.5 w-3.5 rounded-full bg-white shadow-sm ${checked ? "translate-x-[17px]" : "translate-x-[3px]"}`}/></span><span><span className="block text-xs font-medium">{label}</span><span className="mt-1 block text-[11px] leading-5 text-charcoal/40">{description}</span></span></button>; }
function SuccessDialog({ onContinue }: { onContinue: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-charcoal/40 px-6 backdrop-blur-sm"><div className="w-full max-w-md border border-charcoal/10 bg-white p-8 shadow-2xl"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-green-500/10 text-green-600"><Check size={25}/></div><div className="mt-6 text-center"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-bronze">Resource Updated</p><h2 className="mt-2 text-2xl font-medium">Successfully updated</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-charcoal/45">The resource has been successfully updated in your ministry library.</p></div><button type="button" onClick={onContinue} className="mt-8 flex w-full items-center justify-center gap-2 bg-charcoal px-5 py-4 text-[10px] font-semibold uppercase tracking-[0.14em] text-ivory">Continue to Resources<ArrowUpRight size={14}/></button></div></div>; }
